import Head from 'next/head';

export default function Home() {
  return (
    <div className="flex items-center justify-center h-screen bg-gray-100">
      <Head>
        <title>Welcome to ALX Project 0x02</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-center">
        <h1 className="text-4xl font-bold">Welcome to ALX Project 0x02</h1>
      </main>
    </div>
  );
}
